[package]
name = "roguelike"
version = "0.1.0"
authors = ["Ignacio Martinez"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
chargrid_graphical = "0.7"
chargrid = "0.4"
coord_2d = "0.3"
rgb24 = "0.3"
direction = "0.18"